spring.application.name=Springboot-API-REST
spring.web.allow-cors=true

# Configuración de Base de Datos H2 en Memoria para Ventas
spring.datasource.url=jdbc:h2:mem:tienda_ventas;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola de H2 e interfaz Swagger
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path=/swagger-ui.html