name: Deploy Innovatech Chile to AWS

on:
  push:
    branches:
      - main  # ⚠️ Si tu rama principal se llama 'master', cambia esto por 'master'

jobs:
  build-and-push:
    name: Compilar y Subir a Amazon ECR
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout del código
      uses: actions/checkout@v4

    # 2. Configurar las credenciales dinámicas de AWS Academy
    - name: Configurar Credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # 3. Autenticarse en Amazon ECR
    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Construir y subir el FRONTEND (Corregido con guion bajo)
    - name: Build y Push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: front-despacho
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./front_despacho
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # 5. Construir y subir BACKEND VENTAS
    - name: Build y Push Backend Ventas
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: back-ventas
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # 6. Construir y subir BACKEND DESPACHOS
    - name: Build y Push Backend Despachos
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: back-despachos
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG